// This file is generated by scripts/generate_conf_ts.py.
// Do not edit directly.

export interface ParticleRandomConfEntry {
  id: number
  sort_id: number
  name: string
  particle_res: string
  headicon_particle_res: string
  particle_icon: string
  particle_small_icon: string
  particle_big_icon: string
  ratio: number
  StarStickTiling: number
  egg_particle_res?: string
}

export interface ParticleRandomConfType {
  [key: number]: ParticleRandomConfEntry
}

export const PARTICLE_RANDOM_CONF: ParticleRandomConfType = {
  1: {
    "id": 1,
    "sort_id": 4,
    "name": "四角星",
    "particle_res": "Texture2D'/Game/ArtRes/BP/Texture/PetGlassyStar/Tex_PetGlassyStar_003.Tex_PetGlassyStar_003'",
    "headicon_particle_res": "Texture2D'/Game/ArtRes/BP/Texture/PetGlassyStar/Tex_PetGlassyStar_003.Tex_PetGlassyStar_003'",
    "particle_icon": "PaperSprite'/Game/NewRoco/Modules/System/PetUI/PetUIStatic/Frames/img_dazzling_Particle_png.img_dazzling_Particle_png'",
    "particle_small_icon": "PaperSprite'/Game/NewRoco/Modules/System/Appearance/Raw/AppearanceNew/Frames/img_xiaoyise_lingxing_png.img_xiaoyise_lingxing_png'",
    "particle_big_icon": "PaperSprite'/Game/NewRoco/Modules/System/PetUI/PetUIStatic/Frames/img_dazzling_Bg3_png.img_dazzling_Bg3_png'",
    "ratio": 10000,
    "StarStickTiling": 2.2
  },
  2: {
    "id": 2,
    "sort_id": 3,
    "name": "爱心",
    "particle_res": "Texture2D'/Game/ArtRes/BP/Texture/PetGlassyStar/Tex_PetGlassyStar_002.Tex_PetGlassyStar_002'",
    "headicon_particle_res": "Texture2D'/Game/ArtRes/BP/Texture/PetGlassyStar/Tex_PetGlassyStar_002.Tex_PetGlassyStar_002'",
    "particle_icon": "PaperSprite'/Game/NewRoco/Modules/System/PetUI/PetUIStatic/Frames/img_dazzling_Particle3_png.img_dazzling_Particle3_png'",
    "particle_small_icon": "PaperSprite'/Game/NewRoco/Modules/System/Appearance/Raw/AppearanceNew/Frames/img_xiaoyise_xin_png.img_xiaoyise_xin_png'",
    "particle_big_icon": "PaperSprite'/Game/NewRoco/Modules/System/PetUI/PetUIStatic/Frames/img_dazzling_Bg6_png.img_dazzling_Bg6_png'",
    "ratio": 10000,
    "StarStickTiling": 2.2
  },
  3: {
    "id": 3,
    "sort_id": 2,
    "name": "方块",
    "particle_res": "Texture2D'/Game/ArtRes/BP/Texture/PetGlassyStar/Tex_PetGlassyStar_001.Tex_PetGlassyStar_001'",
    "headicon_particle_res": "Texture2D'/Game/ArtRes/BP/Texture/PetGlassyStar/Tex_PetGlassyStar_001.Tex_PetGlassyStar_001'",
    "particle_icon": "PaperSprite'/Game/NewRoco/Modules/System/PetUI/PetUIStatic/Frames/img_dazzling_Particle2_png.img_dazzling_Particle2_png'",
    "particle_small_icon": "PaperSprite'/Game/NewRoco/Modules/System/Appearance/Raw/AppearanceNew/Frames/img_xiaoyise_xingxing_png.img_xiaoyise_xingxing_png'",
    "particle_big_icon": "PaperSprite'/Game/NewRoco/Modules/System/PetUI/PetUIStatic/Frames/img_dazzling_Bg5_png.img_dazzling_Bg5_png'",
    "ratio": 10000,
    "StarStickTiling": 2.2
  },
  4: {
    "id": 4,
    "sort_id": 1,
    "name": "镂空五角星",
    "particle_res": "Texture2D'/Game/ArtRes/BP/Texture/PetGlassyStar/Tex_PetGlassyStar_006.Tex_PetGlassyStar_006'",
    "headicon_particle_res": "Texture2D'/Game/ArtRes/BP/Texture/PetGlassyStar/T_PetGlassyStar_006_UI.T_PetGlassyStar_006_UI'",
    "particle_icon": "PaperSprite'/Game/NewRoco/Modules/System/PetUI/PetUIStatic/Frames/img_dazzling_Particle4_png.img_dazzling_Particle4_png'",
    "particle_small_icon": "PaperSprite'/Game/NewRoco/Modules/System/Appearance/Raw/AppearanceNew/Frames/img_xiaoyise_loukongxing_png.img_xiaoyise_loukongxing_png'",
    "particle_big_icon": "PaperSprite'/Game/NewRoco/Modules/System/PetUI/PetUIStatic/Frames/img_dazzling_Bg10_png.img_dazzling_Bg10_png'",
    "ratio": 10000,
    "egg_particle_res": "Texture2D'/Game/ArtRes/BP/Texture/PetGlassyStar/T_PetGlassyStar_006_RandomEgg.T_PetGlassyStar_006_RandomEgg'",
    "StarStickTiling": 1.0
  }
}
