// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: com_monster.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonsterSettleStatus int32

const (
	MonsterSettleStatus_MonsterSettleStatus__PB3_ZERO MonsterSettleStatus = 0
	MonsterSettleStatus_MONSTER_SETTLE_NONE           MonsterSettleStatus = 0
	MonsterSettleStatus_BATTLE_DEFEAT                 MonsterSettleStatus = 1
	MonsterSettleStatus_BATTLE_CAPTURE                MonsterSettleStatus = 2
	MonsterSettleStatus_SCENE_CAPTURE                 MonsterSettleStatus = 3
)

// Enum value maps for MonsterSettleStatus.
var (
	MonsterSettleStatus_name = map[int32]string{
		0: "MonsterSettleStatus__PB3_ZERO",
		// Duplicate value: 0: "MONSTER_SETTLE_NONE",
		1: "BATTLE_DEFEAT",
		2: "BATTLE_CAPTURE",
		3: "SCENE_CAPTURE",
	}
	MonsterSettleStatus_value = map[string]int32{
		"MonsterSettleStatus__PB3_ZERO": 0,
		"MONSTER_SETTLE_NONE":           0,
		"BATTLE_DEFEAT":                 1,
		"BATTLE_CAPTURE":                2,
		"SCENE_CAPTURE":                 3,
	}
)

func (x MonsterSettleStatus) Enum() *MonsterSettleStatus {
	p := new(MonsterSettleStatus)
	*p = x
	return p
}

func (x MonsterSettleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MonsterSettleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_com_monster_proto_enumTypes[0].Descriptor()
}

func (MonsterSettleStatus) Type() protoreflect.EnumType {
	return &file_com_monster_proto_enumTypes[0]
}

func (x MonsterSettleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MonsterSettleStatus.Descriptor instead.
func (MonsterSettleStatus) EnumDescriptor() ([]byte, []int) {
	return file_com_monster_proto_rawDescGZIP(), []int{0}
}

type MonsterDiffInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Height               int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Weight               int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Nature               int32                  `protobuf:"varint,3,opt,name=nature,proto3" json:"nature,omitempty"`
	MutationType         int32                  `protobuf:"varint,4,opt,name=mutation_type,json=mutationType,proto3" json:"mutation_type,omitempty"`
	BloodMixSkillDamType uint32                 `protobuf:"varint,5,opt,name=blood_mix_skill_dam_type,json=bloodMixSkillDamType,proto3" json:"blood_mix_skill_dam_type,omitempty"`
	GlassInfo            *GlassInfo             `protobuf:"bytes,7,opt,name=glass_info,json=glassInfo,proto3" json:"glass_info,omitempty"`
	Voice                int32                  `protobuf:"varint,8,opt,name=voice,proto3" json:"voice,omitempty"`
	Gender               int32                  `protobuf:"varint,9,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MonsterDiffInfo) Reset() {
	*x = MonsterDiffInfo{}
	mi := &file_com_monster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterDiffInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterDiffInfo) ProtoMessage() {}

func (x *MonsterDiffInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_monster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterDiffInfo.ProtoReflect.Descriptor instead.
func (*MonsterDiffInfo) Descriptor() ([]byte, []int) {
	return file_com_monster_proto_rawDescGZIP(), []int{0}
}

func (x *MonsterDiffInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MonsterDiffInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *MonsterDiffInfo) GetNature() int32 {
	if x != nil {
		return x.Nature
	}
	return 0
}

func (x *MonsterDiffInfo) GetMutationType() int32 {
	if x != nil {
		return x.MutationType
	}
	return 0
}

func (x *MonsterDiffInfo) GetBloodMixSkillDamType() uint32 {
	if x != nil {
		return x.BloodMixSkillDamType
	}
	return 0
}

func (x *MonsterDiffInfo) GetGlassInfo() *GlassInfo {
	if x != nil {
		return x.GlassInfo
	}
	return nil
}

func (x *MonsterDiffInfo) GetVoice() int32 {
	if x != nil {
		return x.Voice
	}
	return 0
}

func (x *MonsterDiffInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type CheerMonsterInitInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfId          uint32                 `protobuf:"varint,1,opt,name=conf_id,json=confId,proto3" json:"conf_id,omitempty"`
	Sid             uint64                 `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Tag             uint32                 `protobuf:"varint,3,opt,name=tag,proto3" json:"tag,omitempty"`
	EnterIndex      uint32                 `protobuf:"varint,4,opt,name=enter_index,json=enterIndex,proto3" json:"enter_index,omitempty"`
	Level           uint32                 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	AiStatus        uint64                 `protobuf:"varint,6,opt,name=ai_status,json=aiStatus,proto3" json:"ai_status,omitempty"`
	PreActTag       int32                  `protobuf:"varint,7,opt,name=pre_act_tag,json=preActTag,proto3" json:"pre_act_tag,omitempty"`
	PreActParam     int32                  `protobuf:"varint,8,opt,name=pre_act_param,json=preActParam,proto3" json:"pre_act_param,omitempty"`
	MonsterDiffInfo *MonsterDiffInfo       `protobuf:"bytes,9,opt,name=monster_diff_info,json=monsterDiffInfo,proto3" json:"monster_diff_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheerMonsterInitInfo) Reset() {
	*x = CheerMonsterInitInfo{}
	mi := &file_com_monster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheerMonsterInitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheerMonsterInitInfo) ProtoMessage() {}

func (x *CheerMonsterInitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_monster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheerMonsterInitInfo.ProtoReflect.Descriptor instead.
func (*CheerMonsterInitInfo) Descriptor() ([]byte, []int) {
	return file_com_monster_proto_rawDescGZIP(), []int{1}
}

func (x *CheerMonsterInitInfo) GetConfId() uint32 {
	if x != nil {
		return x.ConfId
	}
	return 0
}

func (x *CheerMonsterInitInfo) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *CheerMonsterInitInfo) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *CheerMonsterInitInfo) GetEnterIndex() uint32 {
	if x != nil {
		return x.EnterIndex
	}
	return 0
}

func (x *CheerMonsterInitInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CheerMonsterInitInfo) GetAiStatus() uint64 {
	if x != nil {
		return x.AiStatus
	}
	return 0
}

func (x *CheerMonsterInitInfo) GetPreActTag() int32 {
	if x != nil {
		return x.PreActTag
	}
	return 0
}

func (x *CheerMonsterInitInfo) GetPreActParam() int32 {
	if x != nil {
		return x.PreActParam
	}
	return 0
}

func (x *CheerMonsterInitInfo) GetMonsterDiffInfo() *MonsterDiffInfo {
	if x != nil {
		return x.MonsterDiffInfo
	}
	return nil
}

var File_com_monster_proto protoreflect.FileDescriptor

const file_com_monster_proto_rawDesc = "" +
	"\n" +
	"\x11com_monster.proto\x12\x04Next\x1a\x14com_base_types.proto\"\x94\x02\n" +
	"\x0fMonsterDiffInfo\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x16\n" +
	"\x06nature\x18\x03 \x01(\x05R\x06nature\x12#\n" +
	"\rmutation_type\x18\x04 \x01(\x05R\fmutationType\x126\n" +
	"\x18blood_mix_skill_dam_type\x18\x05 \x01(\rR\x14bloodMixSkillDamType\x12.\n" +
	"\n" +
	"glass_info\x18\a \x01(\v2\x0f.Next.GlassInfoR\tglassInfo\x12\x14\n" +
	"\x05voice\x18\b \x01(\x05R\x05voice\x12\x16\n" +
	"\x06gender\x18\t \x01(\x05R\x06gender\"\xae\x02\n" +
	"\x14CheerMonsterInitInfo\x12\x17\n" +
	"\aconf_id\x18\x01 \x01(\rR\x06confId\x12\x10\n" +
	"\x03sid\x18\x02 \x01(\x04R\x03sid\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\rR\x03tag\x12\x1f\n" +
	"\venter_index\x18\x04 \x01(\rR\n" +
	"enterIndex\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12\x1b\n" +
	"\tai_status\x18\x06 \x01(\x04R\baiStatus\x12\x1e\n" +
	"\vpre_act_tag\x18\a \x01(\x05R\tpreActTag\x12\"\n" +
	"\rpre_act_param\x18\b \x01(\x05R\vpreActParam\x12A\n" +
	"\x11monster_diff_info\x18\t \x01(\v2\x15.Next.MonsterDiffInfoR\x0fmonsterDiffInfo*\x8f\x01\n" +
	"\x13MonsterSettleStatus\x12!\n" +
	"\x1dMonsterSettleStatus__PB3_ZERO\x10\x00\x12\x17\n" +
	"\x13MONSTER_SETTLE_NONE\x10\x00\x12\x11\n" +
	"\rBATTLE_DEFEAT\x10\x01\x12\x12\n" +
	"\x0eBATTLE_CAPTURE\x10\x02\x12\x11\n" +
	"\rSCENE_CAPTURE\x10\x03\x1a\x02\x10\x01b\x06proto3"

var (
	file_com_monster_proto_rawDescOnce sync.Once
	file_com_monster_proto_rawDescData []byte
)

func file_com_monster_proto_rawDescGZIP() []byte {
	file_com_monster_proto_rawDescOnce.Do(func() {
		file_com_monster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_monster_proto_rawDesc), len(file_com_monster_proto_rawDesc)))
	})
	return file_com_monster_proto_rawDescData
}

var file_com_monster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_monster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_monster_proto_goTypes = []any{
	(MonsterSettleStatus)(0),     // 0: Next.MonsterSettleStatus
	(*MonsterDiffInfo)(nil),      // 1: Next.MonsterDiffInfo
	(*CheerMonsterInitInfo)(nil), // 2: Next.CheerMonsterInitInfo
	(*GlassInfo)(nil),            // 3: Next.GlassInfo
}
var file_com_monster_proto_depIdxs = []int32{
	3, // 0: Next.MonsterDiffInfo.glass_info:type_name -> Next.GlassInfo
	1, // 1: Next.CheerMonsterInitInfo.monster_diff_info:type_name -> Next.MonsterDiffInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_com_monster_proto_init() }
func file_com_monster_proto_init() {
	if File_com_monster_proto != nil {
		return
	}
	file_com_base_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_monster_proto_rawDesc), len(file_com_monster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_monster_proto_goTypes,
		DependencyIndexes: file_com_monster_proto_depIdxs,
		EnumInfos:         file_com_monster_proto_enumTypes,
		MessageInfos:      file_com_monster_proto_msgTypes,
	}.Build()
	File_com_monster_proto = out.File
	file_com_monster_proto_goTypes = nil
	file_com_monster_proto_depIdxs = nil
}
