// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpc_options.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RealTypeOfInt int32

const (
	RealTypeOfInt_RealTypeOfInt__PB3_ZERO RealTypeOfInt = 0
	RealTypeOfInt_RT_UINT8                RealTypeOfInt = 1
	RealTypeOfInt_RT_INT8                 RealTypeOfInt = 2
	RealTypeOfInt_RT_UINT16               RealTypeOfInt = 3
	RealTypeOfInt_RT_INT16                RealTypeOfInt = 4
)

// Enum value maps for RealTypeOfInt.
var (
	RealTypeOfInt_name = map[int32]string{
		0: "RealTypeOfInt__PB3_ZERO",
		1: "RT_UINT8",
		2: "RT_INT8",
		3: "RT_UINT16",
		4: "RT_INT16",
	}
	RealTypeOfInt_value = map[string]int32{
		"RealTypeOfInt__PB3_ZERO": 0,
		"RT_UINT8":                1,
		"RT_INT8":                 2,
		"RT_UINT16":               3,
		"RT_INT16":                4,
	}
)

func (x RealTypeOfInt) Enum() *RealTypeOfInt {
	p := new(RealTypeOfInt)
	*p = x
	return p
}

func (x RealTypeOfInt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RealTypeOfInt) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_options_proto_enumTypes[0].Descriptor()
}

func (RealTypeOfInt) Type() protoreflect.EnumType {
	return &file_rpc_options_proto_enumTypes[0]
}

func (x RealTypeOfInt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RealTypeOfInt.Descriptor instead.
func (RealTypeOfInt) EnumDescriptor() ([]byte, []int) {
	return file_rpc_options_proto_rawDescGZIP(), []int{0}
}

type NullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullRequest) Reset() {
	*x = NullRequest{}
	mi := &file_rpc_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullRequest) ProtoMessage() {}

func (x *NullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullRequest.ProtoReflect.Descriptor instead.
func (*NullRequest) Descriptor() ([]byte, []int) {
	return file_rpc_options_proto_rawDescGZIP(), []int{0}
}

type NullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullResponse) Reset() {
	*x = NullResponse{}
	mi := &file_rpc_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullResponse) ProtoMessage() {}

func (x *NullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullResponse.ProtoReflect.Descriptor instead.
func (*NullResponse) Descriptor() ([]byte, []int) {
	return file_rpc_options_proto_rawDescGZIP(), []int{1}
}

var File_rpc_options_proto protoreflect.FileDescriptor

const file_rpc_options_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_options.proto\x1a google/protobuf/descriptor.proto\"\r\n" +
	"\vNullRequest\"\x0e\n" +
	"\fNullResponse*d\n" +
	"\rRealTypeOfInt\x12\x1b\n" +
	"\x17RealTypeOfInt__PB3_ZERO\x10\x00\x12\f\n" +
	"\bRT_UINT8\x10\x01\x12\v\n" +
	"\aRT_INT8\x10\x02\x12\r\n" +
	"\tRT_UINT16\x10\x03\x12\f\n" +
	"\bRT_INT16\x10\x04b\x06proto3"

var (
	file_rpc_options_proto_rawDescOnce sync.Once
	file_rpc_options_proto_rawDescData []byte
)

func file_rpc_options_proto_rawDescGZIP() []byte {
	file_rpc_options_proto_rawDescOnce.Do(func() {
		file_rpc_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_options_proto_rawDesc), len(file_rpc_options_proto_rawDesc)))
	})
	return file_rpc_options_proto_rawDescData
}

var file_rpc_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_options_proto_goTypes = []any{
	(RealTypeOfInt)(0),   // 0: RealTypeOfInt
	(*NullRequest)(nil),  // 1: NullRequest
	(*NullResponse)(nil), // 2: NullResponse
}
var file_rpc_options_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_options_proto_init() }
func file_rpc_options_proto_init() {
	if File_rpc_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_options_proto_rawDesc), len(file_rpc_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_options_proto_goTypes,
		DependencyIndexes: file_rpc_options_proto_depIdxs,
		EnumInfos:         file_rpc_options_proto_enumTypes,
		MessageInfos:      file_rpc_options_proto_msgTypes,
	}.Build()
	File_rpc_options_proto = out.File
	file_rpc_options_proto_goTypes = nil
	file_rpc_options_proto_depIdxs = nil
}
